version: '3.4'

services:
  front:
    build:
      context: .
    container_name: kiuki-front
    ports:
      - 8080:8080
    command: /bin/sh -c "yarn && yarn dev:serve"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app

  api:
    image: nginx:alpine
    container_name: kiuki-api
    ports:
      - 8085:443
    volumes:
      - .:/usr/share/nginx/html
      - ./api-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
